apiVersion: v1
kind: Service
metadata:
  name: image-classifier
  labels:
    app: image-classifier
spec:
  selector:
    app: image-classifier
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
